### ISSUE TITLE
Hello, I was wondering what's wrong with my example, I follow the instruction but get different result

### ISSUE THREAD

**Issue by twilight0718** [harlanhong/CVPR2022-DaGAN#19]
I follow the instruction, set my parameter as followed:

CUDA_VISIBLE_DEVICES=7 python demo.py  
--config config/vox-adv-256.yaml 
--driving_video source/example.mp4 
--source_image source/example.png 
--checkpoint download/SPADE_DaGAN_vox_adv_256.pth.tar
--kp_num 15 
--generator SPADEDepthAwareGenerator
--result_video results/example_out.mp4
--relative --adapt_scale 

https://user-images.githubusercontent.com/37037808/169028484-142f9de3-acd6-45d6-950d-caacae9f593a.mp4

Is there something wrong with my parameters.

**Comment by harlanhong** [comment]
Hi @twilight0718 ,
Because you just miss an important parameter: find_best_frame. You can run the demo using the following command:

CUDA_VISIBLE_DEVICES=7 python demo.py
--config config/vox-adv-256.yaml
--driving_video source/example.mp4
--source_image source/example.png
--checkpoint download/SPADE_DaGAN_vox_adv_256.pth.tar
--kp_num 15
--generator SPADEDepthAwareGenerator
--result_video results/example_out.mp4
--relative --adapt_scale --find_best_frame

**Comment by twilight0718** [comment]
Appriciated for your reply!

**Comment by Thisisaname1125** [comment]
> 你好[@twilight0718](https://github.com/twilight0718)， 因为你刚好漏了一个重要的参数：find_best_frame。你可以使用以下命令运行该演示：
> 
> CUDA_VISIBLE_DEVICES=7 python demo.py --config config/vox-adv-256.yaml --driving_video source/example.mp4 --source_image source/example.png --checkpoint download/SPADE_DaGAN_vox_adv_256.pth.tar --kp_num 15 --generator SPADEDepthAwareGenerator --result_video results/example_out.mp4 --relative --adapt_scale --find_best_frame

Hello. I'm not proficient in this field. I'm testing with my own dataset. I'd like to ask, if the find_best_frame parameter is used, will the effect be improved? And how much more time will it take approximately? Looking forward to your reply！
