### ISSUE TITLE
Question about the background of images

### ISSUE THREAD

**Issue by KangweiiLiu** [harlanhong/CVPR2022-DaGAN#2]
Thanks for this incredible work!
I've looked at the demo gif on the project homepage, I was wondering about why the background is moving with head movement, is there any way to disentangle the foreground and background？

**Comment by harlanhong** [comment]
Hello,

Because the background of the driving video is moving with the head movement, that of the resulted video is also moving. For the disentanglement of the foreground and background, a simple way is to utilize a segmentation network to segment the extract the human body. We're also investigating further, as we've found that when the human hair is looser, the outer hair is often treated as the background. 

Best,
Fa-Ting Hong
