### ISSUE TITLE
Depth map from paper not reproducable

### ISSUE THREAD

**Issue by mrokuss** [harlanhong/CVPR2022-DaGAN#20]
Hi

Firstly, thank you for this awesome work. However, I tried to reproduce the depth map from the paper using the "demo.py" script and the result is quite different from the one seen in Fig. 9 of the paper.

Result from the paper:
![depthmapDaGAN paper](https://user-images.githubusercontent.com/83580356/169092504-9914e733-68e4-47d6-9526-39f0fa4915bb.png)

Result running the script:
![depthmapDaGAN_myRun](https://user-images.githubusercontent.com/83580356/169093656-e53a21d9-682a-4c28-8828-b8ee46868aaf.png)

Corresponding depth map as pointcloud:
![depthmapDaGAN_myRunPCD](https://user-images.githubusercontent.com/83580356/169093965-2a0e9803-ee1e-4c53-8e8c-7ebce81ab2a2.png)

The Depth map looks way more smooth and facial details like the nose or mouth are completely lost.

**Comment by harlanhong** [comment]
Hi @mrokuss, 

A more detailed depth map can improve the performance. The released depth model is the one that was only trained on VoxCeleb1 in our experiments, and the result of Figure 9 is from the model trained on Voxceleb2. It is trained in the Rebuttal phase. Due to the rules of camera-ready submission, we did not make major changes to the paper, but only added Fig.9 to prove that our depth network can be trained to generate better and more detailed depth maps with a large amount of data. We haven't used this depth model to train our DaGAN yet. I will first release this depth model first and then release the DaGAN checkpoint trained with this depth model.

**Comment by NikitaKononov** [comment]
> ed
Hello)
Would be very cool, if you release model with 512x512 input/output size in the future
You have cool GPU resources important for training, modest students like me don't have such opportunity :(
It will be available to use your model like an high quality talking head-avatar generation for educational platforms for example. 
Would be very cool I think, thanks a lot for your work!
